name: Deploy to DEV.
on:
  push:
    branches: [deploy-to-prod]
jobs:
  deploy:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:
    - name: Fetch, Pull, Deploy
      uses: nanome-ai/plugin-chemical-interactions@deploy-to-prod
      with:
        host: ${{ secrets.PLUGINS_HQ_HOST }}
        username: ${{ secrets.PLUGINS_HQ_USERNAME }}
        key: ${{ secrets.PLUGINS_HQ_SECRET_KEY }}
        port: ${{ secrets.PLUGINS_HQ_PORT }}
