name: Deploy to PROD.
# on:
#   release:
#     types: [published]
on:
  push:
    branches:
      - deploy-to-prod

jobs:
  build:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    steps:
    - name: SSH and deploy
      description: Check out latest tag, build and deploy.
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PLUGINS_HQ_HOST }}
        port: ${{ secrets.PLUGINS_HQ_PORT }}
        username: ${{ secrets.PLUGINS_HQ_USERNAME }}
        key: ${{ secrets.PLUGINS_HQ_SECRET_KEY }}
        script: |
          cd ${{ secrets.PLUGINS_HQ_PROD_PATH }}
          git fetch --tags
          latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $latestTag
          docker-compose build
          docker-compose -f docker-compose-deploy.yml --env-file .env up -d
